import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import CustomCursor from "@/components/CustomCursor";
import ContactUs from "@/components/ContactUs";
import Testimonials from "@/components/Testimonials";
import Gallery from "@/components/Gallery";
import ResponsiveMenuBar from "@/components/ResponsiveMenuBar";
import ClientOnly from "@/components/ClientOnly";
import ThemeRegistry from "@/components/ThemeRegistry";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const GalleryGrid = [
    "images/indian-img-one.jpg",
    "images/indian-img-two.jpg",
    "images/indian-img-three.jpg",
    "images/indian-img-four.jpg",
    "images/indian-img-five.jpg",
    "images/contact-one.jpg",
  ];

  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeRegistry>
          {/* Custom Cursor */}
          <span className="max-md:hidden">
            <ClientOnly>
              <CustomCursor />
            </ClientOnly>
          </span>

          <div className="flex flex-col min-h-screen">
            {/* Navbar */}
            <header className="md:top-[23px] top-[24px] z-50">
              <ClientOnly>
                <ResponsiveMenuBar />
              </ClientOnly>
            </header>

            {/* Page Content */}
            <main className="">{children}</main>

            <ContactUs />
            <Testimonials />
            <Gallery title={"Gallery"} GridItems={GalleryGrid} />

            {/* Footer */}
            <footer className="bg-gray-800 text-white py-4 mt-10">
              <div className="container mx-auto text-center">
                <ClientOnly>
                  <p>
                    &copy; {new Date().getFullYear()} Chess Academy. All rights
                    reserved.
                  </p>
                </ClientOnly>
              </div>
            </footer>
          </div>
        </ThemeRegistry>
      </body>
    </html>
  );
}
